server {
    listen 80;
    root /usr/share/nginx/html;
    index login.html;

    gzip on;
    gzip_types text/html text/css application/javascript application/json;

    error_page 404 /404.html;
    location = /404.html { internal; }
}
